dataset: FiveDatasets
first_split_size: 10
other_split_size: 10
schedule:
- 25
schedule_type: cosine
batch_size: 128
optimizer: Adam
lr: 0.0005
momentum: 0.9
weight_decay: 0
model_type: hyper
model_name: vit_hyper_imnet
max_task: -1
dataroot: data
workers: 4
validation: False
train_aug: True
rand_split: False